name: 🎉 Request a new command
description: Have an idea for a new command? You can request a new command here.
labels: [enhancement,command,under review]
body:
  - type: dropdown
    id: version
    attributes:
      label: 🔢 Version
      description: Which version of Glitter are you currently using?
      options:
        - 🐣 Pre-Release
    validations:
      required: true
  - type: dropdown
    id: command-type
    attributes:
      label: 💻 Command Type
      description: Is this a system command (e.g. slash command) or just a simple text based one?
      options:
        - 💻 System
        - ✍️ Simple
    validations:
      required: true
  - type: input
    id: key
    attributes:
      label: 🗝️ What should the key for the command be?
      description: All commands have a key for invocation requests (e.g. `uptime` to request uptime for a bot).
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 🤔 What should the command do?
      description: If your feature request is related to a problem, describe it clearly.
    validations:
      required: true